export const REFERENCE_DATE="2026-07-15";
export const DEPOSITS={Economy:2000,Compact:3000,SUV:5000,Premium:15000,Utility:7000} as const;
export const INSURANCE={basic:{dailyRate:0,flatFee:0},all_risk:{dailyRate:80,flatFee:0},franchise_buyback:{dailyRate:0,flatFee:500}} as const;
export const DISCOUNTS={LOYAL10:.10,WELCOME5:.05,SUMMER20:.20,FLASH25:.25} as const;
export type Vehicle={id:string;make:string;model:string;category:keyof typeof DEPOSITS;baseDailyRate:number};
const years=(from:string,to:string)=>Math.round((new Date(to).getTime()-new Date(from).getTime())/86400000/365.25*10)/10;
export function verifyDriverEligibility(birthDate:string,licenseIssueDate:string,licenseExpDate:string,referenceDate=new Date().toISOString().slice(0,10),category?:string){const age=Number(referenceDate.slice(0,4))-Number(birthDate.slice(0,4))-(referenceDate.slice(5)<birthDate.slice(5)?1:0);const seniority=years(licenseIssueDate,referenceDate),expired=licenseExpDate<referenceDate,reasons:string[]=[];if(age<21)reasons.push(`Age insufficient: ${age} (minimum 21)`);if(seniority<2)reasons.push(`License seniority insufficient: ${seniority} years (minimum 2)`);if(expired)reasons.push(`License expired: ${licenseExpDate}`);const eligible=!reasons.length,riskCategory=eligible&&age<25?"jeune_conducteur":eligible?"standard":"ineligible";return {eligible,age,licenseSeniorityYears:seniority,licenseExpired:expired,riskCategory,rejectionReasons:reasons,needsHumanReview:eligible&&riskCategory==="jeune_conducteur"&&category==="Premium"};}
export function checkVehicleAvailability(vehicleId:string,startDate:string,endDate:string,bookings:{vehicleId:string;startDate:string;endDate:string;status?:string}[]){const conflicts=bookings.filter(b=>b.vehicleId===vehicleId&&b.status!=="CANCELLED"&&b.startDate<endDate&&b.endDate>startDate);return {available:conflicts.length===0,vehicleId,conflictingBookings:conflicts.length};}
export function calculateTotalPrice(vehicle:Vehicle,days:number,month:number,insurance:keyof typeof INSURANCE="basic",discountCode="",riskCategory="standard",seasonalMultiplier=1){if(!Number.isInteger(days)||days<=0)throw new Error("Rental days must be positive");const insuranceCost=INSURANCE[insurance].dailyRate*days+INSURANCE[insurance].flatFee,baseDeposit=DEPOSITS[vehicle.category],deposit=riskCategory==="jeune_conducteur"?baseDeposit*1.5:baseDeposit,subtotal=vehicle.baseDailyRate*days*seasonalMultiplier+insuranceCost,nominal=DISCOUNTS[discountCode as keyof typeof DISCOUNTS]??0,effective=Math.min(nominal,.15),discountAmount=Math.round(subtotal*effective*100)/100,total=Math.max(subtotal+deposit-discountAmount,deposit);return {vehicleId:vehicle.id,category:vehicle.category,baseDailyRate:vehicle.baseDailyRate,days,month,seasonalMultiplier,insuranceOption:insurance,insuranceCost,deposit,subtotal,discountCode,discountAmount,discountCapped:nominal>.15,discountNote:nominal>.15?"Discount CAPPED at 15%":"",floorApplied:total===deposit,totalPrice:Math.round(total*100)/100,needsHumanReview:deposit>20000};}
export function calculateMileagePenalty(kmDriven:number,kmAllowed:number,extraKmRate=2.5){const kmOverage=Math.max(0,kmDriven-kmAllowed);return {kmDriven,kmAllowed,kmOverage,extraKmRate,penalty:Math.round(kmOverage*extraKmRate*100)/100};}
