import { StateGraph, Annotation, START, END } from "@langchain/langgraph";
import { PostgresSaver } from "@langchain/langgraph-checkpoint-postgres";
import { and, eq, lt, gt, sql } from "drizzle-orm";
import { db } from "@/db/client"; import { bookingLogs, fleetCatalog, seasonalPricingMatrix, rentalPoliciesVectors } from "@/db/schema";
import { KiraaStateSchema, type KiraaState } from "@/lib/schemas/contracts"; import { calculateTotalPrice, checkVehicleAvailability, verifyDriverEligibility, type Vehicle } from "@/lib/engine";
const State=Annotation.Root({state:Annotation<KiraaState>({reducer:(_,v)=>v,default:()=>KiraaStateSchema.parse({requestId:"",rawInput:""})})});
const addTrace=(s:KiraaState,n:string)=>({...s,graphTrace:[...s.graphTrace,n]}); const review=(s:KiraaState,reason:string)=>({...s,needsHumanReview:true,escalationReasons:[...s.escalationReasons,reason]});
function inferIntent(input:string):[KiraaState["intent"],number]{const s=input.toLowerCase();if(/annul|franchise|assurance|kilom/.test(s))return ["policy_query",.75];if(/r.serv|r.serve|book|confirm/.test(s))return ["make_reservation",.7];if(/prix|co.t|combien|promo/.test(s))return ["calculate_total_cost",.7];if(/disponib|available/.test(s))return ["check_availability",.7];if(/permis|.ligib|age/.test(s))return ["validate_eligibility",.7];return ["out_of_scope",.5]}
export async function ingestorNode({state}:typeof State.State){return {state:addTrace(state,"ingestorNode")}}
export async function extractorNode({state}:typeof State.State){let next=addTrace(state,"extractorNode");if(next.ocrConfidence<.85&&next.ocrConfidence>0)next=review(next,"OCR confidence below 0.85");return {state:next}}
export async function intentNode({state}:typeof State.State){let next=addTrace(state,"intentNode");if(next.intentOverride){next={...next,intent:next.intentOverride,intentConfidence:1};}else if(/\b(demain|prochain)\b/i.test(next.rawInput))next={...next,intent:"CLARIFICATION_REQUIRED",validation:{isValid:false,errors:["Ambiguous date: use ISO YYYY-MM-DD"],status:"CLARIFICATION_REQUIRED"}};else {const [intent,confidence]=inferIntent(next.rawInput);next={...next,intent:intent, intentConfidence:confidence};}return {state:next}}
export async function validatorNode({state}:typeof State.State){let next=addTrace(state,"validatorNode");const p=next.params;if(!p.birthDate||!p.licenseIssueDate||!p.licenseExpDate){return {state:{...next,validation:{isValid:false,errors:["Missing required driver-license field"],status:"CLARIFICATION_REQUIRED"},bookingStatus:"CLARIFICATION_REQUIRED"}}}let category:string|undefined;if(p.vehicleId){const [v]=await db.select().from(fleetCatalog).where(eq(fleetCatalog.id,p.vehicleId));category=v?.category}const eligibility=verifyDriverEligibility(p.birthDate,p.licenseIssueDate,p.licenseExpDate,undefined,category);next={...next,eligibilityResult:eligibility,validation:{isValid:eligibility.eligible,errors:eligibility.rejectionReasons,status:eligibility.eligible?"OK":"REJECTED"}};if(eligibility.needsHumanReview)next=review(next,"Young driver (21-24) with Premium vehicle");return {state:next}}
async function rag(query:string){const rows=await db.select({content:rentalPoliciesVectors.content,source:rentalPoliciesVectors.source,score:sql<number>`1 - (embedding <=> ${query})`}).from(rentalPoliciesVectors).orderBy(sql`embedding <=> ${query}`).limit(3).catch(()=>[]);return rows.map(r=>({...r,score:Number(r.score)||0}))}
export async function calculatorNode({state}:typeof State.State){let next=addTrace(state,"calculatorNode"),p=next.params;if(next.intent==="policy_query")return {state:{...next,ragPassages:await rag(next.rawInput),validation:{isValid:true,errors:[],status:"OK"}}};if(!p.vehicleId||!p.startDate||!p.endDate)return {state:{...next,validation:{isValid:false,errors:["Vehicle and ISO rental dates are required"],status:"CLARIFICATION_REQUIRED"}}};const bookings=await db.select().from(bookingLogs).where(and(eq(bookingLogs.vehicleId,p.vehicleId),lt(bookingLogs.startDate,p.endDate),gt(bookingLogs.endDate,p.startDate)));if(next.intent==="check_availability"||next.intent==="make_reservation"){const availability=checkVehicleAvailability(p.vehicleId,p.startDate,p.endDate,bookings);if(!availability.available)return {state:{...next,validation:{isValid:false,errors:[`${availability.conflictingBookings} conflicting booking(s)`],status:"REJECTED"}}}}if(next.intent==="calculate_total_cost"||next.intent==="make_reservation"){if(!next.eligibilityResult.eligible)return {state:next};const [v]=await db.select().from(fleetCatalog).where(eq(fleetCatalog.id,p.vehicleId));if(!v) return {state:{...next,validation:{isValid:false,errors:["Unknown vehicle"],status:"CLARIFICATION_REQUIRED"}}};const month=new Date(`${p.startDate}T00:00:00Z`).getUTCMonth()+1;const [season]=await db.select().from(seasonalPricingMatrix).where(and(eq(seasonalPricingMatrix.month,month),eq(seasonalPricingMatrix.category,v.category)));const price=calculateTotalPrice({id:v.id,make:v.make,model:v.model,category:v.category as Vehicle["category"],baseDailyRate:Number(v.baseDailyRate)},Math.round((Date.parse(p.endDate)-Date.parse(p.startDate))/86400000),month,p.insuranceOption,p.discountCode,next.eligibilityResult.riskCategory as string,Number(season?.multiplier??1));next={...next,priceResult:price};if(price.needsHumanReview)next=review(next,"Security deposit exceeds 20,000 MAD")}return {state:next}}
export async function explainerNode({state}:typeof State.State){const n=addTrace(state,"explainerNode"),e=n.validation.errors.length? n.validation.errors.join("; "):n.intent==="policy_query"?(n.ragPassages[0]?.content??"No matching policy passage found."):`Deterministic result: ${n.validation.isValid===false?"rejected":"validated"}.`;return {state:{...n,explanation:e}}}
export async function reporterNode({state}:typeof State.State){let n=addTrace(state,"reporterNode");if(n.intent==="make_reservation")n={...n,bookingStatus:n.validation.isValid===false?"REJECTED":n.needsHumanReview?"PENDING_REVIEW":"CONFIRMED"};return {state:{...n,report:{finalized:true}}}}
const normalize=(s:typeof State.State)=>s.state.intent.replaceAll("_","").toLowerCase();
let saver: PostgresSaver | undefined;
export async function buildGraph(){const g=new StateGraph(State).addNode("ingestorNode",ingestorNode).addNode("extractorNode",extractorNode).addNode("intentNode",intentNode).addNode("validatorNode",validatorNode).addNode("calculatorNode",calculatorNode).addNode("explainerNode",explainerNode).addNode("reporterNode",reporterNode).addEdge(START,"ingestorNode").addEdge("ingestorNode","extractorNode").addEdge("extractorNode","intentNode").addConditionalEdges("intentNode",s=>({policyquery:"calculatorNode",validateeligibility:"validatorNode",checkavailability:"calculatorNode",calculatetotalcost:"validatorNode",makereservation:"validatorNode"}[normalize(s)]??"explainerNode")).addConditionalEdges("validatorNode",s=>["calculatetotalcost","makereservation"].includes(normalize(s))?"calculatorNode":"explainerNode").addConditionalEdges("calculatorNode",s=>normalize(s)==="makereservation"?"reporterNode":"explainerNode").addEdge("explainerNode","reporterNode").addEdge("reporterNode",END);if(!saver){saver=PostgresSaver.fromConnString(process.env.DATABASE_URL!);await saver.setup()}return g.compile({checkpointer:saver})}
export async function runAgent(state:KiraaState){const graph=await buildGraph();return (await graph.invoke({state},{configurable:{thread_id:state.requestId}})).state}
